
spring:
  datasource:
    url: jdbc:mysql://rm-uf60o48ndya3cm3k4o.mysql.rds.aliyuncs.com:3306/hywy
    username: nw
    password: NWqwertyuiop1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
  session:
    store-type: redis
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  jackson:
    serialization:
      write-dates-as-timestamps: true
  resources:
    cache:
      cachecontrol:
        cache-public: true
      period: 7d
  redis:
    host: localhost
    database: 7

environment:
  path:
    upload: E:/hywy/upload
    temp: E:/hywy/temp

  # 秒滴短信服务 http://www.miaodiyun.com
  sms:
    url: https://api.miaodiyun.com/20150822/industrySMS/sendSMS
    account_sid: 824daecfe8fa49cf946186afac76650b
    auth_token: 78f66c22f6894481a6b1a54fe5d52f71
    template_id: 1170604879
